version: 0.2

phases:
  install:
    commands:
      - echo "install pre-requisites packages for building a frontend static web application"

  build:
    commands:
      - echo "executing build command to build a static web application, Add your build command below"
      - echo "this is a simple web application written in HTML code, so there is no build command"
      - echo "once build is done we need to add /dist folder in artifacts to copy build files in S3 in the pipe stage"
      - echo "Injecting build number into HTML"
      - sed -i "s/BUILD_NUMBER_PLACEHOLDER/$CODEBUILD_BUILD_NUMBER/g" ./S3-static-website/index.html
      - cp ./S3-static-website/index.html ./index.html

artifacts:
  files:
    - index.html
