version: 0.2

phases:
  install:
    commands:
      - echo "install pre-requisites packages for building a frontend static web application"

  build:
    commands:
      - echo "executing build command to build a static web application, Add your build command below"
      - echo "this is a simple web application written in HTML code, so there is no build command"
      - echo "Injecting build number into HTML"
      - sed -i "s/buildNumber/$CODEBUILD_BUILD_NUMBER/g" ./S3-static-website/index.html

artifacts:
  files:
    - index.html
